/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.tunescontrol;

public final class R {
    public static final class anim {
        public static final int fade_down=0x7f040000;
        public static final int fade_up=0x7f040001;
        public static final int slide_right=0x7f040002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_btn_back=0x7f020000;
        public static final int ic_btn_next=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int scrollbar_state2=0x7f020003;
        public static final int stat_notify_musicplayer=0x7f020004;
    }
    public static final class id {
        public static final int action_next=0x7f070014;
        public static final int action_prev=0x7f070013;
        public static final int alpha=0x7f070015;
        public static final int bottom=0x7f070010;
        public static final int control_box=0x7f07000a;
        public static final int control_buttons=0x7f07000b;
        public static final int control_next=0x7f07000e;
        public static final int control_pause=0x7f07000d;
        public static final int control_prev=0x7f07000c;
        public static final int cover=0x7f070000;
        public static final int fadeview=0x7f070001;
        public static final int info_album=0x7f070005;
        public static final int info_artist=0x7f070004;
        public static final int info_box=0x7f070002;
        public static final int info_title=0x7f070003;
        public static final int left=0x7f070011;
        public static final int progress=0x7f070016;
        public static final int right=0x7f070012;
        public static final int seek=0x7f070007;
        public static final int seek_box=0x7f070006;
        public static final int seek_position=0x7f070008;
        public static final int seek_remain=0x7f070009;
        public static final int top=0x7f07000f;
        public static final int volume=0x7f070017;
    }
    public static final class layout {
        public static final int act_control=0x7f030000;
        public static final int act_gesture=0x7f030001;
        public static final int act_pairing=0x7f030002;
        public static final int act_wizard=0x7f030003;
        public static final int dia_text=0x7f030004;
        public static final int gen_expanded=0x7f030005;
        public static final int gen_list=0x7f030006;
        public static final int item_album=0x7f030007;
        public static final int item_artist=0x7f030008;
        public static final int item_fetch=0x7f030009;
        public static final int item_network=0x7f03000a;
        public static final int item_track=0x7f03000b;
        public static final int toa_volume=0x7f03000c;
    }
    public static final class string {
        public static final int albums_album_caption=0x7f060007;
        public static final int albums_empty=0x7f060004;
        public static final int albums_menu_browse=0x7f060006;
        public static final int albums_menu_play=0x7f060005;
        public static final int app_desc=0x7f060001;
        public static final int app_name=0x7f060000;
        public static final int artists_empty=0x7f060008;
        public static final int artists_menu_browse=0x7f06000a;
        public static final int artists_menu_play=0x7f060009;
        public static final int control_menu_artists=0x7f06000e;
        public static final int control_menu_pick=0x7f06000f;
        public static final int control_menu_repeat_all=0x7f060012;
        public static final int control_menu_repeat_none=0x7f060010;
        public static final int control_menu_repeat_one=0x7f060011;
        public static final int control_menu_search=0x7f06000d;
        public static final int control_menu_shuffle_off=0x7f060014;
        public static final int control_menu_shuffle_on=0x7f060013;
        public static final int dia_code=0x7f060027;
        public static final int dia_ipaddress=0x7f060026;
        public static final int item_fetch=0x7f060028;
        public static final int item_network_caption=0x7f06002a;
        public static final int item_network_title=0x7f060029;
        public static final int library_forget=0x7f060018;
        public static final int library_forget_neg=0x7f06001a;
        public static final int library_forget_pos=0x7f060019;
        public static final int library_manual_neg=0x7f06001c;
        public static final int library_manual_pos=0x7f06001b;
        public static final int library_menu_forget=0x7f060017;
        public static final int library_menu_manual=0x7f060016;
        public static final int library_menu_refresh=0x7f060015;
        public static final int notif_caption=0x7f06000c;
        public static final int notif_title=0x7f06000b;
        public static final int pairing_caption1=0x7f06001f;
        public static final int pairing_caption2=0x7f060020;
        public static final int pairing_title=0x7f06001e;
        public static final int search_hint=0x7f060003;
        public static final int search_label=0x7f060002;
        public static final int toast_volume_title=0x7f06002b;
        public static final int tracks_empty=0x7f06001d;
        public static final int wizard_eula=0x7f060023;
        public static final int wizard_neg=0x7f060025;
        public static final int wizard_pos=0x7f060024;
        public static final int wizard_title1=0x7f060021;
        public static final int wizard_title2=0x7f060022;
    }
    public static final class xml {
        public static final int searchable=0x7f050000;
    }
}
